#!/bin/bash

# Plot the residuals graphically on screen on-the-fly
ln -s $1 log

touch ./residual.gp

tee -a ./residual.gp <<END
set logscale y
set title "Residuals"
set ylabel 'Residual'
set xlabel 'Iteration'
END
argc=$#
argv=($@)
for (( j=0; j<argc; j++ ));
do
    if [[ ( j -eq  argc-1  ) && ( j -eq 1 ) ]]; then
        echo  "plot \"< cat log | grep 'Solving for ${argv[j]}' | cut -d' ' -f9 | tr -d ','\" title '${argv[j]}' with lines" >> ./residual.gp
    elif [[ ( j -lt argc-1 ) && ( j -eq 1 ) ]]; then
        echo "plot \"< cat log | grep 'Solving for ${argv[j]}' | cut -d' ' -f9 | tr -d ','\" title '${argv[j]}' with lines,\\" >> ./residual.gp
    elif [[ ( j -eq argc-1 ) ]]; then
        echo "\"< cat log | grep 'Solving for ${argv[j]}' | cut -d' ' -f9 | tr -d ','\" title '${argv[j]}' with lines" >> ./residual.gp
    elif [[ ( j -lt $# ) && ( j -gt 1 ) ]]; then
        echo "\"< cat log | grep 'Solving for ${argv[j]}' | cut -d' ' -f9 | tr -d ','\" title '${argv[j]}' with lines,\\" >> ./residual.gp
    fi
done

tee -a ./residual.gp <<END
pause 0.1 
reread
END

gnuplot ./residual.gp &
pid=$!
echo "If you do not want to monitor residuals graphically , please run:"
echo "$ kill " $pid
